import Head from 'next/head'
import Cover from '@/Components/Cover/Cover.js'
import Date from '@/Components/Date/Date.js'
import Location from '@/Components/Location/Location.js'



export default function Home() {
  return (
    <>
      <Head>
        <title>Ramona e Stefano si sposano 14-9-2024 </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cover />
      <Date />
      <Location />


    </>
  )
}
