import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ramona e Stefano si sposano 14-9-2024 </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="hero" className={`${styles.main} ${inter.className}`}>
        <div className={styles.coverCard}>

          <div className={styles.coverImage}>
            <div>
              <h1 className={styles.title}> ramona & stefano</h1>
              <h3> finalmente sposi</h3>
              <p>Unisciti a noi nel giorno più speciale della nostra vita.</p>
            </div>
          </div>

          <div className={styles.coverInfo}>

            <h3> Sei invitato al nostro matrimonio!</h3>
            <div className='divider'></div>
          
            <div className={styles.coverInfoDetails}>           
              <p> 14 settembre 2024<br />
                  Milano - Trenno<br />
                  Piazza S. Giovanni, 4, 20151<br />
                  Parrocchia S. Giovanni Battista</p>
            </div>

            <a href="#" className='button'>conferma la presenza</a>
          </div>

        </div>
      </main>

      <section id="when" className={styles.when}>
        <div>
          <h2> Non puoi mancare</h2>
          <div className='divider'></div>

          <h5>Segnati la data</h5>
          <div className={styles.date}>
            <h3>14-9-2024</h3>
          </div>

          <div className={styles.aforismo}>
            <p>"La vita non avrebbe senso senza l’amore che ci unisce."</p>
          </div>

          <a className="button">Scopri Come Raggiungerci</a>

        </div>
      </section>
{/* 
      <section id="where">
        <div className="location ricevimento">
          <h2> una location speciale</h2>
          <div>
            <h3>Il ricevimento</h3>
            <p>In via madreperla, 4 </p>
            <p>Castigliano Monzano - Como</p>
            <p>Ore 10.00</p>
          </div>
        </div>

        <div className="location cerimonia">
          <h2> La cerimonia - chiesa san guglielmo</h2>
          <div>
            <h3>La chiesa di san guglielmo</h3>
            <p>In via santa croce, 33</p>
            <p>Castigliano Monzano - Como</p>
            <p>Ore 14.30</p>
          </div>
        </div>
      </section> */}



    </>
  )
}
